REFER_IMG_COLOR = (238, 0, 0)
SMALL_GROUP_SIZE_THRESHOLD = 35     # threshold for distinct small groups and trustful large group(might be folded)
LAYER_GAP_THRESHOLD = 2.75      # threshold for valid echo filling below echo or surrounded echo value gap check
VALID_SURROUNDED_ECHO_RATIO_THRESHOLD = 0.1    # threshold for small group echo filling surrounding check, supposed to be less than 0.5
UNFOLD_GAP_THRESHOLD = 6.5      # threshold for decide whether echo get folded or not
BASE_ECHO_SURROUNDED_RATIO_THRESHOLD = 0.78     # threshold for base echo group filling surrounding check, supposed to be high
OPPOSITE_SURROUNDED_RATIO_THRESHOLD = 0.79      # threshold velocity unfold outer group check
FOLDED_LAYER_NUM = 2    # number of layer that might contain folded echo
OPPOSITE_SURROUNDED_THRESHOLD = 0.1     # threshold for velocity unfold neighbour surrounded ratio check
OPPOSITE_SURROUNDED_LAYER_GAP_THRESHOLD = 3.15   # threshold for opposite mode echo group integration check
